# commando to up: docker-compose up -d
# commando to down: docker-compose down -v
version: '3'

services:
  bomberman-app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules