name: Docker Compose Build and Push with Commit SHA

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME_KENT }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN_KENT }}

      - name: Build the Docker Image
        run: docker-compose -f docker-compose-kent.yml build

      - name: Get the latest commit SHA
        run: echo ${{ github.event.pull_request.head.sha }}

      - name: Say Hello Carlos
        run: echo "Hello Carlos"

      - name: Tag the Docker Image
        run: docker tag kentyucraq/bomberman-app:1.0 kentyucraq/bomberman-app:${{ github.sha }}

      - name: Push the Docker Image
        run: docker push kentyucraq/bomberman-app:${{ github.sha }}

      - name: Log out from Docker Hub
        run: docker logout
