name: Docker Compose Build and Push with Commit SHA

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Determine Docker Hub account
      id: set-docker-account
      run: echo "account=${{ github.actor }}" >> "GITHUB_OUTPUT"

    - name: Set Docker Hub credentials
      run: |
        if [ "${{ steps.set-docker-account.outputs.account }}" = "kentyucra" ]; then
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_HUB_USERNAME_KENT }}" >> "GITHUB_ENV"
          echo "DOCKER_ACCESS_TOKEN=${{ secrets.DOCKER_HUB_ACCESS_TOKEN_KENT }}" >> "GITHUB_ENV"
          echo "DOCKER_COMPOSE_FILE=docker-compose-kent.yml" >> "GITHUB_ENV"
        else
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_HUB_USERNAME_CARLOS }}" >> "GITHUB_ENV"
          echo "DOCKER_ACCESS_TOKEN=${{ secrets.DOCKER_HUB_ACCESS_TOKEN_CARLOS }}" >> "GITHUB_ENV"
          echo "DOCKER_COMPOSE_FILE=docker-compose-carlos.yml" >> "GITHUB_ENV"
        fi

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: $DOCKER_USERNAME
        password: $DOCKER_ACCESS_TOKEN

    - name: Build the Docker Image
      run: docker-compose -f $DOCKER_COMPOSE_FILE build

    - name: Tag the Docker Image
      run: docker tag $DOCKER_USERNAME/bomberman-app:1.0 $DOCKER_USERNAME/bomberman-app:${{ github.event.pull_request.head.sha }}

    - name: Push the Docker Image
      run: docker push $DOCKER_USERNAME/bomberman-app:${{ github.event.pull_request.head.sha }}

    - name: Log out from Docker Hub
      run: docker logout
