name: Deploy to DigitalOcean Droplet 1

on:
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Determine Docker Hub account
        id: set-docker-account
        run: echo "account=${{ github.actor }}" >> "$GITHUB_OUTPUT"

      - name: production host is
        run: echo ${{ vars.PRODUCTION_HOST }}

      - name: Set Variables Based On Account
        env:
          ACCOUNT: ${{ steps.set-docker-account.outputs.account }}
        run: |
          if [ $ACCOUNT = "kentyucra" ]; then
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_HUB_USERNAME_KENT }}" >> "$GITHUB_ENV"
            {
              echo 'SSH_PRIVATE_KEY<<EOF'
              ${{ secrets.SSH_PRIVATE_KEY_KENT}}
              echo EOF  
            } >> "$GITHUB_ENV"
            echo "PORT=3001" >> "$GITHUB_ENV"
            echo "NAME_APP=bomberman-app-kent-test" >> "$GITHUB_ENV"
          else
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_HUB_USERNAME_CARLOS }}" >> "$GITHUB_ENV"
            {
              echo 'SSH_PRIVATE_KEY<<EOF'
              ${{ secrets.SSH_PRIVATE_KEY_CARLOS}}
              echo EOF  
            } >> "$GITHUB_ENV"
            echo "PORT=3002" >> "$GITHUB_ENV"
            echo "NAME_APP=bomberman-app-carlos-test" >> "$GITHUB_ENV"
          fi

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

      - name: SSH and Deploy to Droplet
        run: |
          ssh -o "StrictHostKeyChecking=no" root@${{ vars.PRODUCTION_HOST }} "docker pull $DOCKER_USERNAME/bomberman-app:${{ github.event.pull_request.head.sha }}"
          ssh -o "StrictHostKeyChecking=no" root@${{ vars.PRODUCTION_HOST }} "(docker ps -q -f name=$NAME_APP && docker stop $NAME_APP || echo 'No running container to stop')"
          ssh -o "StrictHostKeyChecking=no" root@${{ vars.PRODUCTION_HOST }} "docker run -d --rm --name $NAME_APP -p $PORT:$PORT $DOCKER_USERNAME/bomberman-app:${{ github.event.pull_request.head.sha }}"
