name: Deploy to DigitalOcean Droplet 1

on:
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: production host is
        run: echo ${{ vars.PRODUCTION_HOST }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_KENT }}

      - name: SSH and Deploy to Droplet
        run: |
          ssh -o "StrictHostKeyChecking=no" root@${{ vars.PRODUCTION_HOST }} "docker pull kentyucraq/bomberman-app:${{ github.event.pull_request.head.sha }}"
          ssh -o "StrictHostKeyChecking=no" root@${{ vars.PRODUCTION_HOST }} "(docker ps -q -f name=bomberman-app-kent-test && docker stop bomberman-app-kent-test || echo 'No running container to stop')"
          ssh -o "StrictHostKeyChecking=no" root@${{ vars.PRODUCTION_HOST }} "docker run -d --rm --name bomberman-app-kent-test -p 3001:3001 kentyucraq/bomberman-app:${{ github.event.pull_request.head.sha }}"
